config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'
  resources :users, only: [:create, :new, :show]
  resources :events, only: [:new, :show, :index, :create]
  get '/events/:id/add_attendee', to: 'events#add_attendee', as: 'add_attendee'
  get '/events/:id/remove_attendee', to: 'events#remove_attendee', as: 'remove_attendee'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :joins, foreign_key: 'event_id'
  has_many :attendees, through: :joins, source: :user
  scope :upcoming_events, -> { where('date > ?', Time.now) }
  scope :past_events, -> { where('date < ?', Time.now) }

  def date_in_words
    self.date.strftime('%A, %b %d, %Y')
  end
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_create :build_token
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :joins, foreign_key: 'user_id'
  has_many :attended_events, through: :joins, source: :event

  def build_token
    if self.token_digest.nil?
      self.token_digest = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64)
    else
      self.update_attribute(:token_digest, Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64))
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end

  def show
    @user = get_user
    @event = Event.find_by(id: params[:id])
  end

  def index
    @events = Event.all
  end

  def create
    @user = User.find_by(token_digest: session[:token])
    @event = @user.events.build(event_params)
    if @event.save
      flash[:success] = 'Event created!'
      redirect_to @event
    else
      flash[:error] = 'Invalid fields'
      render 'new'
    end
  end

  def add_attendee
    @event = Event.find_by(id: params[:id])
    @user = User.find_by(token_digest: session[:token])
    if @event.attendees.reload.where(name: @user.name).any?
      flash[:error] = 'You are already on the list!'
      redirect_to @event
    else
      @event.attendees << @user
      redirect_to @event
    end
  end

  def remove_attendee
    @event = Event.find_by(id: params[:id])
    @user = User.find_by(token_digest: session[:token])
    @event.attendees.delete(@user)
    redirect_to @event
  end


  private

    def event_params
      params.require(:event).permit(:location, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user
      @user.build_token
      log_in(@user)
      redirect_to @user
    else
      flash.now[:error] = 'User doesn\'t exist'
      render 'new'
    end
  end

  def destroy
    session.delete(:token)
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(token_digest: session[:token])
    @upcoming_events = @user.attended_events.upcoming_events
    @past_events = @user.attended_events.past_events
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
    else
      flash.now[:error] = 'Invalid info'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:token] = user.token_digest
  end

  def get_user
    @user ||= User.find_by(token_digest: session[:token])
  end

  def logged_in?
    !!get_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_list.html.erb
<% yield(:event).each do |event| %>
	<li>
		<%= event.location %>
		<br>
		<%= event.date_in_words %>
	</li>
<% end %>

app/views/events/index.html.erb
<h1>All events</h1>

<% if @events.any? %>
	<h3>Upcoming events</h3>
		<% @events.upcoming_events.each do |event| %>
			<li>
				<%= link_to event.location, event %><br><%= event.date_in_words %>
			</li>
		<% end %>
	<h3>Past events</h3>
		<% @events.past_events.each do |event| %>
			<li>
				<%= link_to event.location, event %><br><%= event.date_in_words %>
			</li>
		<% end %>
<% else %>
	<p>There are no events. <%= link_to 'Create one!', new_event_path %></p>
<% end %> 

app/views/events/new.html.erb
<h1>Create event</h1>

<%= form_for :event, url: events_path do |f| %>
	<%= f.label :location %>
	<%= f.text_field :location %>

	<%= f.label :date %>
	<%= f.date_field :date %>
	<%= f.submit 'Create' %>
<% end %>

app/views/events/show.html.erb
<h1>Event</h1>
<p>Creator:</p>
<p><%= @event.creator.name %></p>
<p>Location:</p>
<p><%= @event.location %></p>
<p>Time:</p>
<p><%= @event.date_in_words %></p>

<div>
	<a><%= link_to 'Join this event!', add_attendee_path(@event) %></a>
</div>
<div>
	<% if @event.attendees.any? %>
		<h4>Attendees:</h4>
		<% @event.attendees.each do |attendee| %>
			<li>
				<%= link_to attendee.name, @user %>
			  <% if attendee.name = @user.name %>
			  	<%= link_to	'Remove', remove_attendee_path(@event) %>
			  <% end %>
			</li>
		<% end %>
	<% else %>
		<p>No attendees yet for this event...</p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventprite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <p class="<%= type %>"><%= msg %></p>
    <% end %>
    <%= render 'sessions/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome to Eventprite</h1>
<%= link_to 'Sign up', new_user_path %>
<%= link_to 'Log in', login_path %>

app/views/users/new.html.erb
<h1>User Signup</h1>
<%= form_for :user, url: users_path do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.email_field :email %>

	<%= f.submit 'Sign up!' %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.name %></h1>
<%= link_to 'Create event', new_event_path %>
<%= link_to 'Show all events', events_path %>
<%= link_to 'Log out', logout_path %>

<div>
	<h3>Your events</h3>
	<% if @user.events.any? %>
		<% @user.events.each do |event| %>
			<li><%= link_to event.location, event %>, <%= event.date_in_words %></li>
		<% end %>
	<% else %>
		<p>You have no events!</p>
	<% end %>
</div>
<div>
	<h3>Your attended events</h3>
	<h4>Upcoming events</h4>
	<% if @upcoming_events.any? %>
		<% @upcoming_events.each do |event| %>
			<li>
				<%= event.location %>
				<br>
				<%= event.date_in_words %>
			</li>
		<% end %>
	<% else %>
		<p>You have no plans yet</p>
	<% end %>
	<h4>Past events</h4>
	<% if @past_events.any? %>
		<% @past_events.each do |event| %>
			<li>
				<%= event.location %>
				<br>
				<%= event.date_in_words %>
			</li>
		<% end %>
	<% else %>
		<p>You haven't been to any events yet</p>
	<% end %>
</div>